### ISSUE TITLE
Can't load view once (less than 2 weeks)

### ISSUE THREAD

**Issue by Lupoul** [Schwartzblat/WhatsApp-Web-Plus#28]
Hi !
I know picture stay 2 weeks on WhatsApp, but I can't load old ones. Do you know how to do it? 
I have the arrow but it's infinite loading. And sometimes one is loaded but I don't know why

I tried disconnect / reconnect, it's the same.

And its only for other people pictures, not mine.
Thanks !

**Comment by Schwartzblat** [comment]
WhatsApp made an update and now they remove the metadata of the view once media making it harder to recover.
In theory, I can research it a little bit and remove their data remover and then you will need to sign out and sign in again and maybe it will work.
I won't add it to the extension but maybe I will upload it to the WhatsApp-Web-Tricks.

**Comment by Lupoul** [comment]
It would be great, I really want to get a picture from a friend who can't send it anymore...

Can you ping me if you can do it ? 

Thanks

**Comment by Lupoul** [comment]
Hi @Schwartzblat !
By chance did you have time to look at it ?
I don't want to "push" it, but I know past 2 weeks the picture would be lost, and we would a lot like to not loose it with my friend 🫣
But it's ok if you can't of course.

Cheers

**Comment by Schwartzblat** [comment]
I have a possible solution.
`let set_key_json_recursive = (obj, key, value) => {
    for (let [current_key, current_value] of Object.entries(obj)) {
        if (current_key === key) {
            obj[current_key] = value;
        } else if (typeof current_value === 'object') {
            obj[current_key] = set_key_json_recursive(current_value, key, value);
        }
    }
    return obj;
}


const original_proto = require('WAWebE2EProtoParser').parseMsgProto;
require('WAWebE2EProtoParser').parseMsgProto = function() {
    set_key_json_recursive(arguments[0]);
    return original_proto(...arguments);
}`

Disconnect from your WhatsApp-Web, log in and paste it quickly into the console.
Let me know if it worked, I haven't tested it.
@Lupoul

**Comment by Lupoul** [comment]
Thanks for that @Schwartzblat but it didn't work 🥲
I paste and started it right after login, tried several seconds after too, but it was the same..

**Comment by Schwartzblat** [comment]
I just tried it and it worked perfectly.
You enable the extension + paste the script I added here and only after that scan the qr.
@Lupoul

**Comment by Lupoul** [comment]
Hi !

I tried on chrome (mac) as you said :
- new private tab (so everything is clean)
- enabled the extension (even in private nav)
- went to WhatsApp Webb (qr code not scanned)
- right click -> inspect -> console
- paste the script and enter : console say script launch
- scan the qr code 

Then it tries to log but I have two things:
- the screen stays on 100% loading but never go on my conversations
- I have two batch of error on the console

If I refresh the page it loads conversations but I still can't see old onetime picture from my friend : as usual I can see mines

Do you need more info to try ?

Sorry again, and thanks a lot for your help

**Comment by Schwartzblat** [comment]
Can you give me the errors?

**Comment by Lupoul** [comment]
Hmm in classic navigation mode (no private) I don't have the error but it doesnt load old picture or video from my friend.

I have this (from this morning for exemple)
![CleanShot 2024-09-22 at 13 05 46](https://github.com/user-attachments/assets/81cf7f54-ea14-40cb-b072-5dc50ca5d899)

And here is my console : 
![CleanShot 2024-09-22 at 13 02 57](https://github.com/user-attachments/assets/daab6658-716b-467c-b2e0-cb3cd623c1c5)

I tried disconnect / reconnect, and this is the same.

I don't know if i'm doing something wrong ? 

Thanks again

**Comment by Schwartzblat** [comment]
Did you clear the storage?

**Comment by Lupoul** [comment]
Yes of course,

Before pasting the script ; it's ok ?

**Comment by Lupoul** [comment]
Hello @Schwartzblat 
As I can see on multiple extensions, old pictures can't be shown. Is it like "lost for ever" in your opinion ?
The picture i'm looking for is a good memory, but I need to know if I have to drop the idea to recover it ahah

Thanks

**Comment by Schwartzblat** [comment]
I understand. I am not at home for  a week so I can't really help.
The method I suggested before suppose to work. You can try to do it again and play with it and maybe it will work

**Comment by Lupoul** [comment]
Hi,

I understand too ahah,

I tried several things on several devices, but I always have the same issue : 
- If I clear storage before pasting and launching script, I have the error
- If I try without clear the storage but in private nav, i don't have the error but i can't load old picture (mines are fine, but the other one are not)

Just to be sure : 
- I deleted comment on the main extension to have view once activated, it's fine ?
- I just paste the script you gave, and press "enter" and then login : it's ok ? Juste need to press enter ? Doens't need to change a value ?

After that I don't refresh etc... It's ok ?
