### ISSUE TITLE
The Command @everyone and @admins is not working

### ISSUE THREAD

**Issue by thisaakash** [Schwartzblat/WhatsApp-Web-Plus#29]
The Command @everyone and @admin is not working

**Comment by Schwartzblat** [comment]
Can you give me more information?
It's working on my machine :)

**Comment by GamingwithAnikYT** [comment]
> Can you give me more information? It's working on my machine :)

the @everyone and @admins is getting sent as a normal text message and not mentioning anyone
![image](https://github.com/user-attachments/assets/27196c31-026a-4d5a-9585-42df7b0053a7)

**Comment by ItsKlork** [comment]
The message should end with @everyone iirc

**Comment by Schwartzblat** [comment]
If you can reproduce this bug, open the issue again.
