### ISSUE TITLE
See blue ticks without sending them

### ISSUE THREAD

**Issue by 54m4d** [Schwartzblat/WhatsApp-Web-Plus#32]
Hello, 

I notice that this feature works for some chats but not for others. Is there a specific reason why this might be happening?

**Comment by Schwartzblat** [comment]
Yes. If the person you are chatting with disabled sending read receipts, you wouldn't get them even with the extension :)
Let me know if it's a different problem.

**Comment by 54m4d** [comment]
Alright.
