### ISSUE TITLE
Viewing community members

### ISSUE THREAD

**Issue by YehudaEi** [Schwartzblat/WhatsApp-Web-Plus#33]
Hi,

If I understand correctly, the limitation that does not allow viewing the community members (in the announcement group) is at the client side level.
Is there an option to add watching the members of the community's announcement group?

Yehuda.

**Comment by Schwartzblat** [comment]
That's actually a cool idea. I will have a loot into it.

**Comment by YehudaEi** [comment]
Hi, have you looked this?

**Comment by Schwartzblat** [comment]
Not yet, I had some other things to do before.

**Comment by YehudaEi** [comment]
Small update, it seems this is not possible.
There is a variable called "incognito" which declares that the group is incognito...

The resulting list of participants is very partial and contains identifiers other than the person's phone number (even for people saved in contacts, for whom the display name is the name saved in contacts).

Yehuda.
