### ISSUE TITLE
view once media issue

### ISSUE THREAD

**Issue by creeperita09** [Schwartzblat/WhatsApp-Web-Plus#38]
i am probably just dumb but is it me or did whatsapp fix the thingy where you could see view once images on web?

**Comment by Schwartzblat** [comment]
It is working...
Why do you think it doesn't?

**Comment by nicognz32** [comment]
To add to this, i also cannot see the view once images, it happened after i updated from 1.0.0 to 1.0.8, i then relogged in to whatsapp web and now it says this feature is not compatible with this version of whatsapp web and to update it

After i click the update button nothing happens, i already tried enabling the beta version in the options and it does nothing, i'm not sure how to fix it, it was working well before

**Comment by creeperita09** [comment]
I also tried uncommenting the view once handler and yes WhatsApp did fix it in the latest version of whatsapp web

**Comment by creeperita09** [comment]
update: apparently know it works, idk, it showed a blank picture before

**Comment by Desushie** [comment]
> update: apparently know it works, idk, it showed a blank picture before

Can also confirm it just started working back again, so i guess you can mark this as solved

**Comment by Schwartzblat** [comment]
Great.
