### ISSUE TITLE
Problemas con la visualización de una sola vez

### ISSUE THREAD

**Issue by DarkFireRM** [Schwartzblat/WhatsApp-Web-Plus#49]
Estaba usando esta extension hace 1 semana y me permitia ver las fotos de visualizacion unica que me enviaban, actualize porque no me funcionaba la extension y resulta que ahora deja ver las fotos enviadas para ver una vez.

Anteiormente funcionaba excelente, incluso luego de 1 semana de haber abierto la foto de visualizacion unica podias volver a verla y se mostraba como una imagen normal, pero ahora no me deja visualizarlas nisiquiera.

Hay algun requisito para se cumpla esta funcion?
 
![image](https://github.com/user-attachments/assets/f6783c90-0133-4e53-b478-5fe849272690)

**Comment by Schwartzblat** [comment]
1. Please specify the version of the installed extension.
2. I haven't seen this kind if behaviour before. Please specify the version of your WhatsApp Web (you can find it your cookies).

**Comment by Schwartzblat** [comment]
Oh damn you are right, I have a bug. Working on that.

**Comment by Schwartzblat** [comment]
Fixed in version 1.1.3. Thanks for the report @DarkFireRM !
