### ISSUE TITLE
 View Edited Messages Functionality

### ISSUE THREAD

**Issue by vishu567** [Schwartzblat/WhatsApp-Web-Plus#52]
Currently, WhatsApp does not provide a way to see the edit history of a message once it has been edited. This feature request proposes adding functionality that allows users to view the original version(s) of a message after it has been edited, similar to how message editing works in other messaging platforms like Slack or Discord.

**Use Case:** In situations where the original message is critical (e.g., instructions, important dates, or figures) and has been altered after sending, it would be helpful for users to verify what the original content was. This would provide transparency and prevent miscommunication.

**Proposed Solution:**

Introduce a feature that shows a "View Edited Message" option next to an edited message.
When clicked, it will open a dialog displaying the original and subsequent edits made to the message.
Limit the number of versions to avoid overwhelming users (e.g., show the last 5 edits).
Include timestamps for each version to track when edits were made.
Ensure this feature is available across all platforms (iOS, Android, Web).

**Additional Considerations:**

**Privacy & Security:** Ensure that the edited message history is encrypted, like other messages, and maintain user privacy.
**UI/UX:** Keep the design minimal and user-friendly, possibly integrating an "Edited" label with a small icon or link that opens the history.
**Backward Compatibility:** The feature should not break functionality for users with older app versions who may not support viewing edit history.
**Benefits:**

Reduces misunderstandings or disputes due to edited messages.
Adds transparency in communication.
Helps in maintaining a clear record of important conversations.
**Possible Challenges:**

Storage implications for keeping edit histories.
Maintaining performance efficiency when displaying and storing multiple edits.
Example:

A user sends a message: "Meeting at 5 PM."
The message is edited to: "Meeting at 6 PM."
The recipient should have the ability to click on "View Edited Message" to see that the original message was "Meeting at 5 PM" and it was edited at a certain timestamp.

**Comment by Schwartzblat** [comment]
It's possible.
I hate doing ui/ux job and it's a complicated one.
If you want you can try to add it yourself, it's too much work for me.
Also I already have a support for edited messages (just without any special ui).
