### ISSUE TITLE
Problems opening videos from IOS users in View Once mode

### ISSUE THREAD

**Issue by sovietzin** [Schwartzblat/WhatsApp-Web-Plus#54]
As it says in the title, I'm unable to open videos in View Once mode that are sent from IOS users. 

Besides that, it's a great extension. Thanks for the hard work!

In the image, it says "Unable to play the video."
![image](https://github.com/user-attachments/assets/24ee4fd0-660f-48df-bdc3-4f97a4097611)

**Comment by sovietzin** [comment]
btw, i'm using the most current version of everything (extension, windows, browser...)

**Comment by Benfleck102** [comment]
![image](https://github.com/user-attachments/assets/87b5493e-88da-4b42-a173-e16bb19be194)
click on it several times until the window with the video opens

**Comment by sovietzin** [comment]
> ![image](https://private-user-images.githubusercontent.com/182130573/385821037-87b5493e-88da-4b42-a173-e16bb19be194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MzcyMDQsIm5iZiI6MTczMTUzNjkwNCwicGF0aCI6Ii8xODIxMzA1NzMvMzg1ODIxMDM3LTg3YjU0OTNlLTg4ZGEtNGI0Mi1hMTczLWUxNmJiMTliZTE5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QyMjI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjdhNjNiNTQwMWViYjdjMmRkMTFhYmM3MzIwNzBkNzY0ZDEzYWFlNjQxNDcyZWIyNzQwZGM4N2NkMzAxMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2ZL0dARgxG_OR3uqj1eah_fa6uzXX1YawMQjjcC4_Ak) click on it several times until the window with the video opens

it worked!
OMG MANY THANKS!!!
